version: "3.8"
services:
  nestjs-app:
    build:
      context: .
      dockerfile: ./Dockerfile
    # env_file:
    #   - ./.env
    environment:
      DATABASE_URL: 'mongodb+srv://thang16:rP4PvFOyL3WyXmIC@cluster0.zvfxi2n.mongodb.net/tlcn'
      jwtSecretKey: 'a8GxUCo0au5/wNG0lPRA2XOgKJ9W698jVY+MCzK3eeOD40ov/Fs/zUjxtmqLCWL6D3aCYxduOS08ODclxlBWjg=='
      jwtRefreshToken: 'Vdv7hnAwg9XjpfiSvMUd9omsM6HR+DgVPb+KCuloW/Uqk1d0wpwncnbPAioy5J2g5IidM6+S2Xo/7MI+BU0N6w=='
      CLIENT_URL: 'http://localhost:3000'
      BACKEND_URL: 'http://localhost:4000'
      CLIENT_ADMIN_URL: "http://localhost:5000"
      HOST_EMAIL: smtp.gmail.com
      USER_NAME: 'nguyenhuuthangc7@gmail.com'
      PASSWORD: 'qzazlqaaozoikcqx'
      REDIS_HOST: 'redis-service'
      REDIS_PORT: '6379'
      WEB3_STORAGE_API_KEY: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaWQ6ZXRocjoweGFEZDllYTQxYzRkMjAzMjY0MTBEZTVDNURiRWJBRDhGNzRkMTRjMUUiLCJpc3MiOiJ3ZWIzLXN0b3JhZ2UiLCJpYXQiOjE2OTc0MzA0OTY3MTYsIm5hbWUiOiJ0bGNuIn0.Z-V--B0BFhg5De_3WWILX7EbI2eEy-c0qBahdeOt6DU'
      AWS_S3_ACCESS_KEY: 'AKIAY5E4TAHXWW6FDWGM'
      AWS_S3_SECRET_KEY: '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'
      AWS_S3_REGION: 'ap-southeast-1'
      AWS_BUCKET: 'tlcn-upload'
      ORGANIZATION_ID: 'org-5LLSrr0KdsLdeHGKu7c1UhLu'
      OPENAI_API_KEY: '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'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '4000:4000'
    depends_on:
      - redis
  
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data
volumes:
  redis:
    driver: local