version: "3.8"
services:
  nestjs-app:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - ./.env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /var/run/docker.sock:/var/run/docker.sock
      - nestjs_data:/dist
    ports:
      - '4000:4000'
    depends_on:
      - redis
  
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data
    
  coderunner_php:
    container_name: coderunner_php
    build:
      context: ./code/php
      dockerfile: Dockerfile

  coderunner_python:
    container_name: coderunner_python
    build:
      context: ./code/python
      dockerfile: Dockerfile

  coderunner_java:
    container_name: coderunner_java
    build:
      context: ./code/java
      dockerfile: Dockerfile

  coderunner_javascript:
    container_name: coderunner_javascript
    build:
      context: ./code/javascript
      dockerfile: Dockerfile

  coderunner_typescript:
    container_name: coderunner_typescript
    build:
      context: ./code/typescript
      dockerfile: Dockerfile

  coderunner_cpp:
    container_name: coderunner_cpp
    build:
      context: ./code/cpp
      dockerfile: Dockerfile

  coderunner_webdev:
    container_name: coderunner_webdev
    build:
      context: ./code/webdev
      dockerfile: Dockerfile
volumes:
  redis:
    driver: local
  nestjs_data:
    driver: local