import { Channel, Conversation, Server, User } from "@prisma/client";
import { ServerResponse } from "../dto/server-response.dto";
import { CreateServerInterface } from "../dto/create-server-interface.dto";
import { GetServerDto, LeaveServerDto } from "../dto/get-server.dto";
import { GetChannelServerDto } from "../dto/get-channel-server";
import { GenerateInviteCodeDto } from "../dto/generate-invitecode.dto";
import { CheckInviteCodeDto } from "../dto/check-invitecode.dto";
import { UpdateServerInterface } from "../dto/update-server-interface.dto";
import { UpdateRoleMemberDto } from "../dto/update-role.dto";
import { KickMemberDto } from "../dto/kick-member.dto";
import { AccessChannelGeneralDto, ChannelResponse, CreateChannelDto, DeleteChannelDto, DetailChannelDto, EditChannelDto } from "../dto/channel.dto";
import { CreateConversationDto } from "../dto/conversation.dto";
import { CreateMediaRoomDto } from "../dto/livekit.dto";

export interface ThreadServiceInterface {
    findUserByEmail(email: string): Promise<User>;
    findServerByName(name: string): Promise<Server>;
    isCodeExist(inviteCode: string): Promise<boolean>;
    createServer(payload: CreateServerInterface): Promise<ServerResponse>;
    getServerUser(payload: GetServerDto): Promise<Server[]>;
    getChannelServer(payload: GetChannelServerDto): Promise<Server>;
    generateInviteCode(): Promise<string>;
    generateNewInviteCode(payload: GenerateInviteCodeDto): Promise<Server>;
    checkInviteCode(payload: CheckInviteCodeDto): Promise<ServerResponse>;
    updateServer(payload: UpdateServerInterface): Promise<ServerResponse>;
    checkUserServer(payload: GenerateInviteCodeDto): Promise<ServerResponse>;
    updateRoleMember(payload: UpdateRoleMemberDto): Promise<Server>;
    kickMember(payload: KickMemberDto): Promise<Server>;
    createChannel(payload: CreateChannelDto): Promise<ServerResponse>;
    leaveServer(payload: LeaveServerDto): Promise<ServerResponse>;
    deleteServer(payload: LeaveServerDto): Promise<ServerResponse>;
    editChannel(payload: EditChannelDto): Promise<ServerResponse>;
    deleteChannel(payload: DeleteChannelDto): Promise<ServerResponse>;
    accessChannelGeneral(payload: AccessChannelGeneralDto): Promise<ChannelResponse>;
    detailChannel(payload: DetailChannelDto): Promise<Channel>;
    findConversation(memberOwnerId: string, memberGuestId: string): Promise<Conversation>;
    createNewConversation(memberOwnerId: string, memberGuestId: string): Promise<Conversation>;
    getOrCreateConversation(payload: CreateConversationDto): Promise<Conversation>;
    buildChannelResponse(payload: Channel): ChannelResponse;
    createMediaRoom(payload: CreateMediaRoomDto): Promise<object>;
    buildServerResponse(payload: Server): ServerResponse;
}
