apiVersion: v1
kind: Service
metadata:
    namespace: nestjs-tlcn-namespace
    name: nestjs-service
spec:
    type: LoadBalancer
    ports:
        - port: 4000
          targetPort: 4000
    selector:
        app: nestjs
---
apiVersion: apps/v1
kind: Deployment
metadata:
    namespace: nestjs-tlcn-namespace
    name: nestjs-deployment
spec:
    replicas: 2
    selector:
        matchLabels:
            app: nestjs
    template:
        metadata:
            labels:
                app: nestjs
        spec:
            containers:
                - name: nestjs-k8s
                  image: thang1610/nestjs-k8s
                  ports:
                      - containerPort: 4000
                  envFrom:
                      - secretRef:
                            name: nestjs-kubernetes-secret
